In [48]:
import pandas as pd
import numpy as np

In [49]:
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [50]:
df=pd.read_csv("../data/titanic_train.csv")
df.sample(5)

PassengerId  Survived  Pclass  \
550          551         1       1   
888          889         0       3   
427          428         1       2   
238          239         0       2   
594          595         0       2   

                                                  Name     Sex   Age  SibSp  \
550                        Thayer, Mr. John Borland Jr    male  17.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
427  Phillips, Miss. Kate Florence ("Mrs Kate Louis...  female  19.0      0   
238                    Pengelly, Mr. Frederick William    male  19.0      0   
594                            Chapman, Mr. John Henry    male  37.0      1   

     Parch       Ticket      Fare Cabin Embarked  
550      2        17421  110.8833   C70        C  
888      2   W./C. 6607   23.4500   NaN        S  
427      0       250655   26.0000   NaN        S  
238      0        28665   10.5000   NaN        S  
594      0  SC/AH 29037   26.0000   NaN        S

In [51]:
df.drop(columns=['PassengerId','Name','Ticket'],inplace=True)

In [52]:
df.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [53]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')

In [54]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [55]:
df.drop(columns=['Cabin'],inplace=True)

In [56]:
df.count()

Survived    891
Pclass      891
Sex         891
Age         714
SibSp       891
Parch       891
Fare        891
Embarked    889
dtype: int64

In [57]:
df['Age'].mean()

29.69911764705882

In [58]:
df['Age'].sum()/df['Age'].count()

29.69911764705882

In [59]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [60]:
df['Compeer']=df['SibSp']+df['Parch']

In [61]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),
                                               df['Survived'],
                                               test_size=0.2,
                                               shuffle=True,
                                               random_state=42)

In [62]:
X_train.shape

(712, 8)

In [63]:
X_train.sample(5)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Compeer
524       3    male   NaN      0      0   7.2292        C        0
878       3    male   NaN      0      0   7.8958        S        0
726       2  female  30.0      3      0  21.0000        S        3
583       1    male  36.0      0      0  40.1250        C        0
229       3  female   NaN      3      1  25.4667        S        4

In [64]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [65]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [66]:
df['Compeer'].unique()

array([ 1,  0,  4,  2,  6,  5,  3,  7, 10], dtype=int64)

In [67]:
age_impute=SimpleImputer()
emberk_impute=SimpleImputer(strategy='most_frequent')

In [68]:
X_train_age=age_impute.fit_transform(X_train[['Age']])
X_test_age=age_impute.fit_transform(X_test[['Age']])

In [69]:
X_train_emberk=emberk_impute.fit_transform(X_train[['Embarked']])
X_test_emberk=emberk_impute.fit_transform(X_test[['Embarked']])

In [70]:
X_train.sample(10)

Pclass     Sex   Age  SibSp  Parch      Fare Embarked  Compeer
302       3    male  19.0      0      0    0.0000        S        0
510       3    male  29.0      0      0    7.7500        Q        0
393       1  female  23.0      1      0  113.2750        C        1
534       3  female  30.0      0      0    8.6625        S        0
307       1  female  17.0      1      0  108.9000        C        1
724       1    male  27.0      1      0   53.1000        S        1
851       3    male  74.0      0      0    7.7750        S        0
28        3  female   NaN      0      0    7.8792        Q        0
646       3    male  19.0      0      0    7.8958        S        0
610       3  female  39.0      1      5   31.2750        S        6

In [71]:
# one hot encoding to sex and embarked

ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')


X_train_sex=ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked=ohe_embarked.fit_transform(X_train_emberk)


X_test_sex=ohe_sex.fit_transform(X_test[['Sex']])
x_test_embarked=ohe_embarked.fit_transform(X_test_emberk)

In [72]:
X_train_new=X_train.drop(columns=['Age','Sex',"Embarked"])
X_test_new=X_test.drop(columns=['Age','Sex','Embarked'])

In [73]:
X_train_transformed=np.concatenate((X_train_new,X_train_age,X_train_embarked,X_train_sex),axis=1)
X_test_transfromed=np.concatenate((X_test_new,X_test_age,x_test_embarked,X_test_sex),axis=1)

In [74]:
X_train_transformed.shape

(712, 11)

In [75]:
cls=DecisionTreeClassifier()

cls.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [93]:
X_test_transfromed[0,:]

array([ 3.        ,  1.        ,  1.        , 15.2458    ,  2.        ,
       30.50584507,  1.        ,  0.        ,  0.        ,  0.        ,
        1.        ])

In [76]:
y_pred=cls.predict(X_test_transfromed)

In [89]:
X_test_transfromed.shape

(179, 11)

In [77]:
from sklearn.metrics import accuracy_score

In [78]:
accuracy_score(y_pred=y_pred,y_true=y_test)

0.7597765363128491

In [85]:
import pickle
from pathlib import Path

In [87]:
model_dir=Path('../models')

model_dir.mkdir(parents=True,
                exist_ok=True
         )

In [88]:
pickle.dump(ohe_sex,open('../models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('../models/ohe_embarked.pkl','wb'))
pickle.dump(cls,open('../models/clf.pkl','wb'))