In [4]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [6]:
df=pd.read_csv("../../data/titanic_train.csv")
df.sample(5)

PassengerId  Survived  Pclass  \
617          618         0       3   
505          506         0       1   
564          565         0       3   
571          572         1       1   
720          721         1       2   

                                                Name     Sex   Age  SibSp  \
617  Lobb, Mrs. William Arthur (Cordelia K Stanlick)  female  26.0      1   
505       Penasco y Castellana, Mr. Victor de Satode    male  18.0      1   
564                   Meanwell, Miss. (Marion Ogden)  female   NaN      0   
571    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female  53.0      2   
720                Harper, Miss. Annie Jessie "Nina"  female   6.0      0   

     Parch             Ticket      Fare Cabin Embarked  
617      0          A/5. 3336   16.1000   NaN        S  
505      0           PC 17758  108.9000   C65        C  
564      0  SOTON/O.Q. 392087    8.0500   NaN        S  
571      0              11769   51.4792  C101        S  
720      1             248727   33.0000   NaN        S

In [7]:
df.drop(columns=['PassengerId','Name','Ticket'],inplace=True)

In [8]:
df.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')

In [10]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [11]:
df.drop(columns=['Cabin'],inplace=True)

In [12]:
df.count()

Survived    891
Pclass      891
Sex         891
Age         714
SibSp       891
Parch       891
Fare        891
Embarked    889
dtype: int64

In [13]:
df['Age'].mean()

29.69911764705882

In [14]:
df['Age'].sum()/df['Age'].count()

29.69911764705882

In [15]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [16]:
df['Compeer']=df['SibSp']+df['Parch']

In [17]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),
                                               df['Survived'],
                                               test_size=0.2,
                                               shuffle=True,
                                               random_state=42)

In [18]:
X_train.shape

(712, 8)

In [19]:
X_train.sample(5)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Compeer
685       2    male  25.0      1      2  41.5792        C        3
750       2  female   4.0      1      1  23.0000        S        2
789       1    male  46.0      0      0  79.2000        C        0
356       1  female  22.0      0      1  55.0000        S        1
466       2    male   NaN      0      0   0.0000        S        0

In [20]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [21]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [22]:
df['Compeer'].unique()

array([ 1,  0,  4,  2,  6,  5,  3,  7, 10], dtype=int64)

In [23]:
age_impute=SimpleImputer()
emberk_impute=SimpleImputer(strategy='most_frequent')

In [24]:
X_train_age=age_impute.fit_transform(X_train[['Age']])
X_test_age=age_impute.fit_transform(X_test[['Age']])

In [25]:
X_train_emberk=emberk_impute.fit_transform(X_train[['Embarked']])
X_test_emberk=emberk_impute.fit_transform(X_test[['Embarked']])

In [26]:
X_train.sample(10)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Compeer
188       3    male  40.0      1      1  15.5000        Q        2
702       3  female  18.0      0      1  14.4542        C        1
748       1    male  19.0      1      0  53.1000        S        1
261       3    male   3.0      4      2  31.3875        S        6
348       3    male   3.0      1      1  15.9000        S        2
303       2  female   NaN      0      0  12.3500        Q        0
443       2  female  28.0      0      0  13.0000        S        0
634       3  female   9.0      3      2  27.9000        S        5
228       2    male  18.0      0      0  13.0000        S        0
249       2    male  54.0      1      0  26.0000        S        1

In [27]:
# one hot encoding to sex and embarked

ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')


X_train_sex=ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked=ohe_embarked.fit_transform(X_train_emberk)


X_test_sex=ohe_sex.fit_transform(X_test[['Sex']])
x_test_embarked=ohe_embarked.fit_transform(X_test_emberk)

In [28]:
X_train_new=X_train.drop(columns=['Age','Sex',"Embarked"])
X_test_new=X_test.drop(columns=['Age','Sex','Embarked'])

In [29]:
X_train_transformed=np.concatenate((X_train_new,X_train_age,X_train_embarked,X_train_sex),axis=1)
X_test_transfromed=np.concatenate((X_test_new,X_test_age,x_test_embarked,X_test_sex),axis=1)

In [30]:
X_train_transformed.shape

(712, 11)

In [31]:
cls=DecisionTreeClassifier()

cls.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [32]:
X_test_transfromed[0,:]

array([ 3.        ,  1.        ,  1.        , 15.2458    ,  2.        ,
       30.50584507,  1.        ,  0.        ,  0.        ,  0.        ,
        1.        ])

In [33]:
y_pred=cls.predict(X_test_transfromed)

In [34]:
X_test_transfromed.shape

(179, 11)

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
accuracy_score(y_pred=y_pred,y_true=y_test)

0.7486033519553073

In [37]:
import pickle
from pathlib import Path

In [41]:
model_dir=Path('../../models')

model_dir.mkdir(parents=True,
                exist_ok=True
         )

In [42]:
pickle.dump(ohe_sex,open('../../models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('../../models/ohe_embarked.pkl','wb'))
pickle.dump(cls,open('../../models/clf.pkl','wb'))